### ISSUE TITLE
mejorar las Invoices 

### ISSUE THREAD

**Issue by oriana8** [jcarranz97/tienda-web#6]
Mover a estado --> Reservado cuando un producto sea agregado a una invoiced, si la cantidad de abono es igual al total, marcarlos como no disponibles.

**Comment by jcarranz97** [comment]
Lo agregamos en el backend, entonces el commit se hizo en este repo
https://github.com/jcarranz97/tienda/pull/8

**Comment by oriana8** [comment]
TE AMO
