### ISSUE TITLE
Saldo restante en invoices

### ISSUE THREAD

**Issue by oriana8** [jcarranz97/tienda-web#7]
Agregar saldo restante en los apartados.

**Comment by jcarranz97** [comment]
Arreglado!
Puse el REMANING BALANCE en la columna de invoices
![image](https://github.com/user-attachments/assets/8c921e89-1f43-4df8-b12e-046db5498abc)

Y tambien el remaining balance aparece en el invoice details
![image](https://github.com/user-attachments/assets/9f8d72c1-4043-4e22-a325-9d39917331ed)

**Comment by oriana8** [comment]
MUY BIEN MI AMOR
